name: FantasyNPC
version: ${pluginVersion}
main: net.fantasyrealms.fantasynpc.FantasyNPC
author: 'HappyAreaBean'
apiVersion: 1.13
softDepends: ['PlaceholderAPI', 'DecentHolograms', 'Holograms', 'HolographicDisplays', 'CMI', 'ProtocolLib']