name: FantasyNPC
version: ${pluginVersion}
main: net.fantasyrealms.fantasynpc.FantasyNPC
author: 'HappyAreaBean'
api-version: 1.13
softdepend: [PlaceholderAPI, DecentHolograms, Holograms, HolographicDisplays, CMI]