package net.fantasyrealms.fantasynpc.constants;

import de.exlll.configlib.NameFormatters;
import de.exlll.configlib.YamlConfigurationProperties;
import net.fantasyrealms.fantasynpc.config.converter.LocationStringConverter;
import net.fantasyrealms.fantasynpc.util.Utils;
import org.bukkit.Location;

public class ConfigProperties {
	public static YamlConfigurationProperties CONFIG = YamlConfigurationProperties.newBuilder()
			.setNameFormatter(NameFormatters.IDENTITY)
			.header(String.join("\n",
					Utils.FULL_LINE,
					" ",
					"  _____           _                  _   _ ____   ____ ",
					" |  ___|_ _ _ __ | |_ __ _ ___ _   _| \\ | |  _ \\ / ___|",
					" | |_ / _` | '_ \\| __/ _` / __| | | |  \\| | |_) | |    ",
					" |  _| (_| | | | | || (_| \\__ \\ |_| | |\\  |  __/| |___ ",
					" |_|  \\__,_|_| |_|\\__\\__,_|___/\\__, |_| \\_|_|    \\____|",
					"                               |___/                   ",
					" ",
					"                                       Config file - config.yml",
					" ",
					Utils.FULL_LINE,
					" ",
					"Welcome to the settings of FantasyNPC!",
					"https://fantasyrealms.net",
					" ",
					Utils.FULL_LINE
			))
			.build();

	public static YamlConfigurationProperties NPC_DATA = YamlConfigurationProperties.newBuilder()
			.outputNulls(true)
			.setNameFormatter(NameFormatters.IDENTITY)
			.addSerializer(Location.class, new LocationStringConverter())
			.header(String.join("\n",
					Utils.FULL_LINE,
					" ",
					"  _____           _                  _   _ ____   ____ ",
							" |  ___|_ _ _ __ | |_ __ _ ___ _   _| \\ | |  _ \\ / ___|",
							" | |_ / _` | '_ \\| __/ _` / __| | | |  \\| | |_) | |    ",
							" |  _| (_| | | | | || (_| \\__ \\ |_| | |\\  |  __/| |___ ",
							" |_|  \\__,_|_| |_|\\__\\__,_|___/\\__, |_| \\_|_|    \\____|",
							"                               |___/                   ",
					" ",
					"                                       NPC Data file - npcs.yml",
					" ",
					Utils.FULL_LINE,
					" ",
					"Welcome to the nps data file of FantasyNPC!",
					"https://fantasyrealms.net",
					" ",
					Utils.FULL_LINE,
					" ",
					"!!!! W A R N I N G !!!!",
					"Please do not edit this file directly if you don't know how it work!",
					" ",
					Utils.FULL_LINE
			))
			.build();
}
